### ISSUE TITLE
Is this a full functioning version of Umbraco ?

### ISSUE THREAD

**Issue by mikkeljohnsen** [Shazwazza/Umbraco9#2]
I mean, is there UI for setting up and managing the pages.

I'm new to Umbraco, have been waiting for years, for a version that could run on Linux and PostgreSQL (or MariaDB).

Also is plugins possible i this version (if at all on Umbraco) ?

Could a Docker be created from Microsofts Docker image ?

**Comment by Shazwazza** [comment]
absolutely not :)

This is a work in progress porting over Umbraco v8 to ASP.Net Core. The Core project is building and working, i'm still in the process of porting over the web project.

**Comment by Shazwazza** [comment]
Also, this repo was a proof of concept repo, the AspNetCore development for Umbraco is done in my fork here on the dev-v9 branch: https://github.com/Shazwazza/Umbraco-CMS/tree/dev-v9

... but still very much a work in progress.

**Comment by mikkeljohnsen** [comment]
Hi Shazwazza

Is there any work on this branch ?

I tried to port the xproj to the new 2017 csproj format. But could not compile.

With the pace of the development of version 8. A release for ASP.NET Core is 3-4 years away. That is really a shame. Since a large procent (more than 50%) of potential users are cut off. (No one goes back to Windows, from Unix).

**Comment by Shazwazza** [comment]
I haven't had time to work on this for a long time. The pace of v8 is misleading. We've been working hard on a lot of underlying things that we'd need for v8 but are being delivered in 7.6 and 7.7, this is work that would need to be done in v8 anyways. Direct v8 work will recommence very soon and v8 is a requirement to make this (aka v9) work because we need to remove all of the dead/old/webforms/etc... code which will be part of v8.
There's probably a bit of work to make this work on ASP.NET vLatest with csproj, i haven't had time to look into that at all. There will be a large merge coming up from v7 -> v8 which will take some time, then there will be another large merge from v8 -> this branch which will also take some time. 
In any case, if you want to keep working on this codebase you are more then welcome to help out, any work done here isn't going to waste.
