### ISSUE TITLE
You still actively working on this bro?

### ISSUE THREAD

**Issue by nigel-dewar** [Shazwazza/Umbraco9#3]
G'day Shannon mate,

you still working on this bro? As in, an Umbraco on .net core project?

Cheers

Nige

**Comment by Shazwazza** [comment]
Umbraco v8 needs to come out in order for this to be possible, there's still a ton of cleanup required to get things working on ASP.NET Core and webforms/incompatible stuff to be removed.

This fork will need to be re-forked with the latest v8 branch and essentially start again since there's an insane amount changed in both asp.net core and v8 since this was originally done.

**Comment by nigel-dewar** [comment]
Thanks mate this makes sense!

Cheers

Nige

**Comment by p-m-j** [comment]
Now that v8 is out, is this still the appropriate place for those keen to contribute to porting efforts?

**Comment by Shazwazza** [comment]
No this is ancient and in no way mergeable with v8, .NET Core has evolved tremendously since then. Porting over v8 now as is will be much easier. The Umbraco.Core project will almost just do it, but will require removing references to System.Web, The Umbraco.Web project will be much harder due to all of the controller, auth, and other web changes. There's plenty of other challenges but it will be easier now than it was before. I'll make sure to close this repo.
